minimumReleaseAge: 21600
minimumReleaseAgeExclude:
  - "@himenon/openapi-parameter-formatter"
  - "@himenon/openapi-typescript-code-generator"

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - lefthook
