name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://npm.pkg.github.com
          scope: "@Himenon"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: |
          pnpm build

  release-github-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://npm.pkg.github.com
          scope: "@Himenon"
          cache: "pnpm"
      - run: pnpm install
      - run: |
          pnpm build
          pnpm release:github:registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-npm-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm release:npm:registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
